# Generated by Django 5.1.4 on 2026-05-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_attempt_and_testrun'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='submission',
            new_name='submissions_attempt_5d1ca4_idx',
            old_name='submissions_attempt_e4d3b9_idx',
        ),
        migrations.AlterField(
            model_name='testrun',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
