# Generated by Django 5.1.4 on 2026-05-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_submission_xp_awarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='xp_earned',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
