# Generated by Django 5.1.4 on 2026-05-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_testcase_assignment_fk'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='exercise',
            new_name='exercises_e_languag_3a678f_idx',
            old_name='exercises_e_languag_e6b4c1_idx',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text="Hidden cases run during grading but aren't shown to students."),
        ),
    ]
