# Generated by Django 5.1.4 on 2026-05-09 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_assignmentmetrics'),
        ('exercises', '0003_rename_exercises_e_languag_e6b4c1_idx_exercises_e_languag_3a678f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='concepts',
            field=models.ManyToManyField(blank=True, related_name='exercises', to='exercises.concept'),
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=1, help_text='1 = first hint shown.')),
                ('content', models.TextField()),
                ('penalty', models.PositiveSmallIntegerField(default=0, help_text='XP deducted from the eventual submission grade if revealed.')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structured_hints', to='exercises.exercise')),
            ],
            options={
                'ordering': ('exercise', 'level'),
                'unique_together': {('exercise', 'level')},
            },
        ),
        migrations.CreateModel(
            name='ConceptMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0, help_text='0..1; EMA over passed/total ratio.')),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_records', to='exercises.concept')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_mastery', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-score',),
                'indexes': [models.Index(fields=['student'], name='exercises_c_student_f7c99a_idx'), models.Index(fields=['concept'], name='exercises_c_concept_c0fb78_idx')],
                'unique_together': {('student', 'concept')},
            },
        ),
        migrations.CreateModel(
            name='HintReveal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revealed_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hint_reveals', to='assignments.assignmentattempt')),
                ('hint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reveals', to='exercises.hint')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hint_reveals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('attempt', 'revealed_at'),
                'indexes': [models.Index(fields=['attempt'], name='exercises_h_attempt_1f16a2_idx')],
                'unique_together': {('attempt', 'hint')},
            },
        ),
    ]
