# Generated by Django 5.1.4 on 2026-05-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cheatevent',
            new_name='realtime_ch_attempt_4db6c9_idx',
            old_name='realtime_ch_attempt_d7c0f1_idx',
        ),
        migrations.RenameIndex(
            model_name='cheatevent',
            new_name='realtime_ch_kind_6d185e_idx',
            old_name='realtime_ch_kind_2bc491_idx',
        ),
        migrations.AlterField(
            model_name='cheatevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
