# Generated by Django 5.1.4 on 2026-05-09 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_assignmentmetrics'),
        ('classrooms', '0001_initial'),
        ('realtime', '0002_rename_realtime_ch_attempt_d7c0f1_idx_realtime_ch_attempt_4db6c9_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('editor_snapshot', 'Editor snapshot'), ('run_code', 'Run code'), ('submission', 'Submission'), ('testcase_pass', 'Test case passed'), ('testcase_fail', 'Test case failed'), ('hint_open', 'Hint opened'), ('paste', 'Paste'), ('copy', 'Copy'), ('blur', 'Tab/window blur'), ('focus', 'Tab/window focus'), ('fullscreen_exit', 'Left fullscreen'), ('devtools', 'DevTools opened'), ('dom_tamper', 'DOM tampered'), ('key_combo', 'Forbidden key combo'), ('contextmenu', 'Right-click menu'), ('network_open', 'Window opened'), ('visibility', 'Page hidden'), ('suspect', 'Suspicious activity'), ('attempt_start', 'Attempt started'), ('attempt_end', 'Attempt ended'), ('presence_online', 'Presence online'), ('presence_offline', 'Presence offline'), ('status_change', 'Status change')], max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='assignments.assignment')),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='assignments.assignmentattempt')),
                ('classroom', models.ForeignKey(blank=True, help_text='Null for solo-practice events.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='classrooms.classroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['classroom', '-created_at'], name='realtime_cl_classro_e778a3_idx'), models.Index(fields=['user', '-created_at'], name='realtime_cl_user_id_4c94bb_idx'), models.Index(fields=['assignment', '-created_at'], name='realtime_cl_assignm_bc2a85_idx'), models.Index(fields=['attempt', '-created_at'], name='realtime_cl_attempt_26e40b_idx'), models.Index(fields=['type'], name='realtime_cl_type_2fa443_idx')],
            },
        ),
        migrations.CreateModel(
            name='CodeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('trigger', models.CharField(choices=[('run', 'Run'), ('submit', 'Submit'), ('debounce', 'Debounce')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='assignments.assignmentattempt')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['attempt', '-created_at'], name='realtime_co_attempt_b4f44c_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('offline', 'Offline'), ('idle', 'Idle'), ('online', 'Online'), ('progressing', 'Progressing'), ('struggling', 'Struggling'), ('stuck', 'Stuck')], default='offline', max_length=16)),
                ('stuck_score', models.FloatField(default=0)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_pass_at', models.DateTimeField(blank=True, null=True)),
                ('progress', models.FloatField(default=0, help_text='0..1 fraction of testcases passed.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assignments.assignment')),
                ('active_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assignments.assignmentattempt')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_statuses', to='classrooms.classroom')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['classroom', 'status'], name='realtime_st_classro_1a959a_idx'), models.Index(fields=['status'], name='realtime_st_status_ba05f2_idx')],
            },
        ),
    ]
