# Generated by Django 5.1.4 on 2026-05-08 18:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_id', models.UUIDField(db_index=True)),
                ('runner_job_id', models.CharField(blank=True, max_length=64)),
                ('image', models.CharField(max_length=200)),
                ('cpu_limit', models.CharField(max_length=16)),
                ('memory_limit', models.CharField(max_length=16)),
                ('timeout_seconds', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('timed_out', models.BooleanField(default=False)),
            ],
        ),
    ]
