# Generated by Django 5.1.4 on 2026-05-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(choices=[('python', 'Python')], default='python', max_length=20)),
                ('starter_code', models.TextField(blank=True)),
                ('expected_stdout', models.TextField(blank=True, help_text='If set, submissions are auto-graded by exact stdout match.')),
                ('max_points', models.PositiveIntegerField(default=100)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
