# Generated by Django 5.1.4 on 2026-05-08 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_extend_assignment_and_attempt'),
        ('exercises', '0003_rename_exercises_e_languag_e6b4c1_idx_exercises_e_languag_3a678f_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='assignmentattempt',
            new_name='assignments_assignm_1234c7_idx',
            old_name='assignments_assignm_a4f7d3_idx',
        ),
        migrations.RenameIndex(
            model_name='assignmentattempt',
            new_name='assignments_status_cdcbc5_idx',
            old_name='assignments_status_8d3e91_idx',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='exercise',
            field=models.ForeignKey(blank=True, help_text='If unset, this is a teacher-authored custom assignment with its own testcases.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='exercises.exercise'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='max_attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 = unlimited'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='strict_mode',
            field=models.BooleanField(default=True, help_text='Fullscreen lock + paste/copy/contextmenu/devtools blockers active.'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='If set, each student gets this many minutes from first start.', null=True),
        ),
        migrations.AlterField(
            model_name='assignmentattempt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
