# Generated by Django 5.1.4 on 2026-05-08 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_rename_assignments_assignm_a4f7d3_idx_assignments_assignm_1234c7_idx_and_more'),
        ('classrooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='solo_owner',
            field=models.ForeignKey(blank=True, help_text='Set when classroom is null — student practicing on own.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solo_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='classroom',
            field=models.ForeignKey(blank=True, help_text='Null = student-owned solo practice (see solo_owner).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='classrooms.classroom'),
        ),
    ]
