# Generated by Django 5.1.4 on 2026-05-09 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_unique_active_attempt'),
        ('exercises', '0003_rename_exercises_e_languag_e6b4c1_idx_exercises_e_languag_3a678f_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_started', models.PositiveIntegerField(default=0)),
                ('students_completed', models.PositiveIntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0)),
                ('median_solve_seconds', models.PositiveIntegerField(default=0)),
                ('avg_runs', models.FloatField(default=0)),
                ('hint_usage_pct', models.FloatField(default=0)),
                ('common_errors', models.JSONField(blank=True, default=list, help_text='[{label,count}] sorted desc — exception types, failed testcase names, stderr fingerprints.')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='assignments.assignment')),
                ('most_failed_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='exercises.testcase')),
            ],
        ),
    ]
